### ISSUE TITLE
seed ipfs file to webtorrent

### ISSUE THREAD

**Issue by wdfsinap** [webtorrent/webtorrent-hybrid#84] opened 2018-08-05 03:17 UTC
one problem of webtorrent is that one have to backup a file after seeding to webtorrent otherwise the tracker may can't find one node having the seed. if using ipfs file as the backup, things are solved. 

question: how to seed a ipfs file(https://ipfs.io/ipfs/<hash>) to webtorrent?
thanks

**Comment by SilentBot1** [comment] 2018-08-05 20:54
Hey @wdfsinap,

From the looks of ipfs.io, you could use a WebSeed and point to the ipfs.io public gateway (`ipfs.io/ipfs/hash/`) so that the torrents content will be downloaded from the ipfs.io network. As there may not be a seeding node with the metadata, you will likely have to use a `.torrent` file for distribution in this scenario. 

I'm going to close the issue as it's not a issue with the library but feel free to continue the conversation, I'll be happy to help you with any further questions.

Hope this helps!

**Closed by SilentBot1** 2018-08-05 20:54 UTC

**Comment by wdfsinap** [comment] 2018-08-06 06:14
@SilentBot1 maybe I am wrong. I find the ipfs is very slow to load a video file after I upload the file to the ipfs network. Maybe ipfs is fine for small files such as text, images, but for movies or other big files, it is too slow to load on the website. is there any alternative for big file storage if I choose webtorrent? can we combine with google drive and webtorrent?

**Comment by SilentBot1** [comment] 2018-08-06 08:51
@wdfsinap, 

I'm by no means an expert on ipfs, my knowledge on it is based on about 15 minutes of reading the documentation, but from my understanding when using the public gateway, it uses a distributed hash table to find your node which contains the file and then streams it through the gateway to your client. 

This DHT lookup is likely the cause of the large latency so possibly referencing a node which you know has the file on it (the node you uploaded it to), instead of the gateway would be one way to lower the latency.

I'm not too familiar with Google Drive's API, but I don't believe it's possible as there is a lack of CORS, you would be better off using something like Amazon S3 (+ Cloudfront for scale) or a HTTP(s) server with your content on it.

All the best.
